server:
  port: 8082

spring:
  profiles: dev
  mvc:
    throw-exception-if-no-handler-found: true
  datasource:
    url: jdbc:mysql://localhost:3307/price_service?autoReconnect=true&useSSL=false
    username: user
    password: password
    driver-class-name: com.mysql.jdbc.Driver
    platform: mysql
  flyway:
    user: user
    password: password
    url: jdbc:mysql://localhost:3307/price_service?autoReconnect=true&useSSL=false
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka