spring:
  application:
    name: price-service
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL57Dialect
    open-in-view: false
    properties:
      hibernates:
        jdbc:
          time_zone: UTC
  output:
    ansi:
      enabled: always