spring:
  application:
    name: registry-service
  profiles:
    active: dev
  output:
    ansi:
      enabled: always
server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false


